# Exercises

Do your work for this exercise in either a python file named `simulation.py` or a jupyter notebook named `simulation.ipynb`

In [2]:
import numpy as np
import pandas as pd


### Q1 How likely is it that you roll doubles when rolling two dice?

In [142]:
rolls=np.random.choice([1,2, 3, 4,5, 6], size=(100_000, 2))
rolls

array([[2, 5],
       [1, 1],
       [5, 4],
       ...,
       [2, 6],
       [3, 3],
       [1, 4]])

In [143]:
df = pd.DataFrame(rolls)

In [144]:
def doubles(rolls):
    return rolls[0] == rolls[1].all()

pd.DataFrame(rolls).apply(doubles, axis = 1).mean()

0.16603

### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [34]:
# Heads = 1, tails = 0
flips = np.random.choice([1, 0], size=(10_000, 8))
flips

array([[1, 1, 0, ..., 1, 0, 1],
       [1, 1, 1, ..., 0, 0, 1],
       [0, 0, 1, ..., 0, 0, 1],
       ...,
       [0, 1, 0, ..., 0, 0, 1],
       [1, 1, 0, ..., 0, 0, 1],
       [1, 1, 0, ..., 1, 1, 1]])

In [36]:
sum_flips = flips.sum(axis = 1)

In [37]:
# If heads is exacly 3
(sum_flips == 3).mean()

0.2209

In [38]:
# If more than 3 heads
(sum_flips > 3).mean()

0.6302

### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [42]:
# 1 = data science, 0 = web dev
students = np.random.choice([1,0], p=[.25, .75], size=(10_000, 2))

In [45]:
sum_students = students.sum(axis = 1)
sum_students

array([1, 0, 1, ..., 0, 0, 1])

In [47]:
(sum_students == 2).mean()

0.0618

### 4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [80]:
# buy = 3, not buy = 0
snacks = np.random.normal(3, (1.5), (10_000, 5))
snacks

array([[4.80337052, 5.70782342, 4.01037531, 2.92600143, 0.22000176],
       [4.24364988, 3.94223986, 4.1233445 , 3.80452758, 2.51692656],
       [3.60715528, 3.66531159, 2.67650438, 2.39345   , 3.52488881],
       ...,
       [3.0722294 , 3.31301218, 1.85478312, 0.92400005, 2.6768903 ],
       [2.52917433, 2.58108716, 5.32068407, 4.23175155, 6.50084959],
       [7.26759691, 2.90712364, 3.80123546, 3.52736088, 4.46484382]])

In [81]:
p_snacks = snacks.sum(axis=1)
p_snacks

array([17.66757244, 18.63068839, 15.86731007, ..., 11.84091505,
       21.1635467 , 21.96816071])

In [82]:
(p_snacks <= 16 ).mean()

0.6175

### 5. Compare Heights

* Men have an average height of 178 cm and standard deviation of 8cm.
* Women have a mean of 170, sd = 6cm.
* If a man and woman are chosen at random, P(woman taller than man)?

In [92]:
men = np.random.normal(178, (8), (10_000))
women = np.random.normal(170, (6), (10_000))
p_women = men < women
(p_women).mean()
    

0.2081

### 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

In [101]:
# download is corrupted = 0, not currupted = 1
downloads = np.random.choice([1,0], p=[.996,0.004], size=(10_000, 50))

In [102]:
sum_downloads = downloads.sum(axis=1)

In [105]:
(sum_downloads == 50).mean()

0.8217

In [107]:
# If its 100 students
double_downloads = np.random.choice([1,0], p=[.996,0.004], size=(10_000, 100))

In [110]:
sum_doubles = double_downloads.sum(axis = 1)

In [111]:
(sum_doubles == 100).mean()

0.6685

#### What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [112]:
triple_downloads = np.random.choice([1,0], p=[.996,0.004], size=(10_000, 150))

In [114]:
sum_triples = triple_downloads.sum(axis=1) 

In [116]:
# 45% chance we observe an istallation issue
(sum_triples < 150).mean()

0.4429

#### How likely is it that 450 students all download anaconda without an issue?

In [117]:
all_students = np.random.choice([1,0], p=[.996,0.004], size=(10_000, 450))

In [118]:
sum_all = all_students.sum(axis=1)

In [119]:
(sum_all == 450).mean()

0.1649

### There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [122]:
# truck in park = 1, no truck = 0
trucks = np.random.choice([1,0], p=[.7, .3], size=(10_000, 7))

In [123]:
sum_trucks = trucks.sum(axis=1)
sum_trucks

array([5, 7, 4, ..., 3, 5, 5])

In [125]:
(sum_trucks <= 3).mean()

0.126

#### How likely is it that a food truck will show up sometime this week?

In [126]:
# truck in park = 1, no truck = 0
week_trucks = np.random.choice([1,0], p=[.7, .3], size=(10_000, 4))

In [127]:
sum_week = week_trucks.sum(axis=1)

In [128]:
(sum_week >= 1).mean()

0.9908

### 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [134]:
b_day = np.random.choice([1, 0], p=[(1/365), 364/365], size=(100_000, 23))

In [136]:
sum_b_day = b_day.sum(axis=1)

In [137]:
(sum_b_day >= 1).mean()

0.06176

In [141]:
# if 40 ppl
b_day_40 = np.random.choice([1, 0], p=[(1/365), 364/365], size=(100_000, 40))
sum_b_day_40 = b_day_40.sum(axis=1)

(sum_b_day_40 >= 1).mean()

0.10444